image:
  repository: docker.io/erofeevdma/aith-team1-core-api
  tag: b6453281e7413f3e35e8c7059130b503b763168e
  pullPolicy: Always

replicaCount: 1

resources:
  requests:
    cpu: "300m"
    memory: "512Mi"
  limits:
    cpu: "300m"
    memory: "512Mi"

configMap:
  name: ""  # Будет переопределено из родительского чарта

secret:
  name: ""  # Будет переопределено из родительского чарта

service:
  port: 8000
  targetPort: 8000

# RBAC Configuration
rbac:
  enabled: false  # Set to true to enable RBAC-based secret isolation




