{{- if or .Values.rbac.enabled (and .Values.global.rbac .Values.global.rbac.enabled) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "frontend.fullname" . }}-secret-reader
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["{{ include "frontend.secretName" . }}"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "frontend.fullname" . }}-secret-binding
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "frontend.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "frontend.fullname" . }}-secret-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}

