{{- if .Values.rbac.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-postgres-sa

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-rabbitmq-sa

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-core-api-sa

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-workers-sa

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-frontend-sa
{{- end }}