image:
  authService:
    repository: erofeevdma/aith-team1-auth-service
    tag: latest
    pullPolicy: Always

core-api:
  image:
    repository: docker.io/erofeevdma/aith-team1-core-api
    tag: b6453281e7413f3e35e8c7059130b503b763168e
    pullPolicy: Always
  replicaCount: 1
  configMap:
    name: ""  # Будет использовано имя из основного чарта
  secret:
    name: "hr-assist-secrets"  # Соответствует existingSecretName из основного чарта

frontend:
  image:
    repository: docker.io/erofeevdma/aith-team1-frontend
    tag: b6453281e7413f3e35e8c7059130b503b763168e
    pullPolicy: Always
  replicaCount: 1
  configMap:
    name: ""  # Будет использовано имя из основного чарта
  secret:
    name: "hr-assist-secrets"  # Соответствует existingSecretName из основного чарта

rabbitmq:
  image: rabbitmq:3.13-management-alpine
  username: guest
  password: "" 
  vhost: "/"
  port: 5672
  uiPort: 15672

postgres:
  image: postgres:16
  username: postgres
  password: ""
  db: hr_assist
  port: 5432

ingress:
  enabled: true
  host: ""
  className: nginx
  tls: false

env:
  openaiModelName: "gpt-4.1-mini"
  openaiApiBase: "https://api.openai.com/v1"
  logLevel: INFO

secrets:
  useExternal: false
  useExisting: true
  existingSecretName: "hr-assist-secrets"
  
  vault:
    path: "team1/hr-assist"
    username: ""
  
  openaiApiKey: ""
  kcClientSecret: ""
  rabbitmqPassword: ""
  postgresPassword: ""

job-description-service:
  image:
    repository: docker.io/erofeevdma/aith-team1-job-description-worker
    tag: b6453281e7413f3e35e8c7059130b503b763168e
    pullPolicy: Always
  replicaCount: 1
  configMap:
    name: ""
  secret:
    name: "hr-assist-secrets"

question-generation-service:
  image:
    repository: docker.io/erofeevdma/aith-team1-question-generation-worker
    tag: b6453281e7413f3e35e8c7059130b503b763168e
    pullPolicy: Always
  replicaCount: 1
  configMap:
    name: ""
  secret:
    name: "hr-assist-secrets"

resume-evaluation-service:
  image:
    repository: docker.io/erofeevdma/aith-team1-resume-evaluation-worker
    tag: b6453281e7413f3e35e8c7059130b503b763168e
    pullPolicy: Always
  replicaCount: 1
  configMap:
    name: ""
  secret:
    name: "hr-assist-secrets"