---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-core-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: core-api
  template:
    metadata:
      labels:
        app: core-api
    spec:
      {{- if or .Values.rbac.enabled (and .Values.global.rbac .Values.global.rbac.enabled) }}
      serviceAccountName: {{ .Release.Name }}-core-api-sa
      {{- end }}
      containers:
        - name: core-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name | default .Values.global.configMapName | default (printf "%s-config" .Release.Name) }}
            - secretRef:
                name: {{- if or .Values.rbac.enabled (and .Values.global.rbac .Values.global.rbac.enabled) }}{{ .Release.Name }}-core-api-secrets{{- else }}{{ .Values.secret.name | default .Values.global.secretName | default (printf "%s-secrets" .Release.Name) }}{{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

