{{- if or .Values.rbac.enabled (and .Values.global.rbac .Values.global.rbac.enabled) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "core-api.serviceAccountName" . }}
  labels:
    {{- include "core-api.labels" . | nindent 4 }}
{{- end }}

