---
{{- include "rabbitmq.validateValues" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rabbitmq.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rabbitmq.selectorLabels" . | nindent 8 }}
    spec:
      {{- if or .Values.rbac.enabled (and .Values.global.rbac .Values.global.rbac.enabled) }}
      serviceAccountName: {{ include "rabbitmq.serviceAccountName" . }}
      {{- end }}
      containers:
        - name: rabbitmq
          image: "{{ .Values.image }}"
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.username | quote }}
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "rabbitmq.secretName" . }}
                  key: RABBITMQ_DEFAULT_PASS
            - name: RABBITMQ_DEFAULT_VHOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "rabbitmq.configMapName" . }}
                  key: RABBITMQ_DEFAULT_VHOST
          command: ["/bin/bash", "-c"]
          args:
            - |
              # Enable Prometheus plugin for KEDA metrics
              rabbitmq-plugins enable rabbitmq_prometheus
              # Start RabbitMQ server
              docker-entrypoint.sh rabbitmq-server
          ports:
            - containerPort: {{ .Values.port }}
              name: amqp
            - containerPort: {{ .Values.uiPort }}
              name: management
            - containerPort: 15692
              name: prometheus
          {{- if .Values.probes }}
          livenessProbe:
            {{- toYaml .Values.probes.liveness | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.probes.readiness | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}


