{{- if or .Values.rbac.enabled (and .Values.global.rbac .Values.global.rbac.enabled) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rabbitmq.serviceAccountName" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
{{- end }}







