---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
  ports:
    - name: amqp
      port: {{ .Values.port }}
      targetPort: amqp
    - name: management
      port: {{ .Values.uiPort }}
      targetPort: management
    - name: prometheus
      port: 15692
      targetPort: prometheus







