---
{{- $secretName := "" }}
{{- if or .Values.rbac.enabled (and .Values.global.rbac .Values.global.rbac.enabled) }}
{{- $secretName = printf "%s-workers-secrets" .Release.Name }}
{{- else }}
{{- $secretName = .Values.secret.name | default (printf "%s-secrets" .Release.Name) }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-job-descr-worker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: job-descr-worker
  template:
    metadata:
      labels:
        app: job-descr-worker
        egress: openai-via-squid
    spec:
      {{- if or .Values.rbac.enabled (and .Values.global.rbac .Values.global.rbac.enabled) }}
      serviceAccountName: {{ .Release.Name }}-workers-sa
      {{- end }}
      containers:
        - name: job-descr-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name | default (printf "%s-config" .Release.Name) }}
            - secretRef:
                name: {{ $secretName }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

