image:
  repository: docker.io/erofeevdma/aith-team1-frontend
  tag: b6453281e7413f3e35e8c7059130b503b763168e
  pullPolicy: Always

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "100m"
    memory: "256Mi"

configMap:
  name: ""

secret:
  name: ""

service:
  port: 8501
  targetPort: 8501

rbac:
  enabled: false




