---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "question-generation-service.deploymentName" . }}
  labels:
    {{- include "question-generation-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "question-generation-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "question-generation-service.selectorLabels" . | nindent 8 }}
        egress: openai-via-squid
    spec:
      {{- if or .Values.rbac.enabled (and .Values.global.rbac .Values.global.rbac.enabled) }}
      serviceAccountName: {{ include "question-generation-service.serviceAccountName" . }}
      {{- end }}
      containers:
        - name: question-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "question-generation-service.configMapName" . }}
            - secretRef:
                name: {{ include "question-generation-service.secretName" . }}
          {{- if .Values.probes }}
          livenessProbe:
            {{- toYaml .Values.probes.liveness | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.probes.readiness | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

